### ISSUE TITLE
'openin_any' is not available for MiKTeX (Window) users

### ISSUE THREAD

**Issue by cweedall** [nlct/texosquery#3]
When running certain queries, such as `--cwd`, permissions are required to access the file(s) or director(y/ies).  This can be debugged via `texosquery --debug --cwd`.  The `kpsewhich -var-value=openin_any` command is run to obtain the access value.  (I assume this also applies to `openout_any` for certain commands...but have no verified this).  An example of the debug error is:

    texosquery-jre8: Can't determine openin value, assuming 'p'
    texosquery-jre8: "kpsewhich '-var-value=openin_any'" failed with exit code: 1
    java.io.IOException: "kpsewhich '-var-value=openin_any'" failed with exit code: 1
        at com.dickimawbooks.texosquery.TeXOSQuery.kpsewhich(TeXOSQuery.java:135)
        at com.dickimawbooks.texosquery.TeXOSQuery.isReadPermitted(TeXOSQuery.java:312)
        at com.dickimawbooks.texosquery.TeXOSQuery.getCwd(TeXOSQuery.java:960)
        at com.dickimawbooks.texosquery.TeXOSQuery$2.action(TeXOSQuery.java:4033)
        at com.dickimawbooks.texosquery.QueryAction.doAction(QueryAction.java:367)
        at com.dickimawbooks.texosquery.TeXOSQuery.processArgs(TeXOSQuery.java:4002)
        at com.dickimawbooks.texosquery.TeXOSQueryJRE8.main(TeXOSQueryJRE8.java:369)
    texosquery-jre8: Read access forbidden by openin_any=p (has absolute path outside TEXMFOUTPUT): C:\PATH\tests
    texosquery-jre8: Read access not permitted for the current directory

In MiKTeX 2.9 (possibly other versions?) on Windows, there is no `texmf.cnf` file, nor is there an `openin_any` (or `openout_any`) value set anywhere in the installation.  For MiKTeX users, this makes these type of commands impossible to access or use.

I am opening this issue as a two-part request - a documentation workaround (temp) and a more permanent solution:

1. Include the workaround in the documentation: set the environment variable `openin_any` with a value of `a` prior to running the compilation.  This can be done via either:
    - `set openin_any=a` in the command line, then `pdflatex.exe ...`, `xelatex.exe ...`, etc. etc. (requires manual run or a .bat file of commands, not supported directly in MiKTeX)
    - Advanced system settings -> System properties -> Environment Variables -> add user or system variable `openin_any` with value `a`. (No change of MiKTeX settings or .bat file, but requires system settings change which is less desirable, in my opinion)

2. Include a check for MiKTeX installation first (see below), followed by a check for the variable `EnableWrite18` with either value `t` ("total" - i.e. completely insecure) or `p` (`p` is "partial" for MiKTeX, vs. the standard "paranoid" denotation in `texmf.cnf`).  There is also an `f` value...but I can't find the meaning of it in the documentation.
    - A way to check that `kpsewhich` is running from the MiKTeX installation is to run `findtexmf kpsewhich.exe` and parse the string for "miktex\bin\".  From the default installation folder on a 64-bit MiKTeX instalation, I get `C:\Program Files\MiKTeX 2.9\miktex\bin\x64\kpsewhich.exe`, for example.

**Comment by nlct** [comment]
As a temporary fix, version 1.3 will use `a` as the fallback for `texosquery.jar` and `texosquery-jre5.jar`, if `openin_any` isn't set. The stricter `texosquery-jre8.jar` still uses `p` as the fallback. I don't have a MikTeX installation, so it will take me longer to work out how to check for MikTeX's `EnableWrite18`, but at least v1.3 should provide a suitable stopgap solution. I'll upload v1.3 to CTAN shortly, but I'll leave this issue open.

**Comment by cweedall** [comment]
When I was trying to figure out this issue, I created a thread over on Stack Exchange [see link](https://tex.stackexchange.com/questions/361173/texosquery-doesnt-play-well-with-miktex-using-xelatex/361186?noredirect=1#comment890956_361186).  Ulrike suggested a feature request for `kpsewhich` to "broadcast" `openin_any` - this, of course, is a MiKTeX feature request.

I bring this up here for a couple reasons.  First, I am less familiar with both `texosquery` _and_ MiKTeX's internals.  For example, if `texosquery` has any other variable check requirements (possibly such as `openout_any`), it would be important to include these all at once rather than piecemeal.

Second, I thought perhaps you would have an idea of which approach (MiKTeX feature request vs. handled purely via `texosquery`) would be better in the long run?  I'm guessing feature request to avoid idiosyncracies, but wanted to check first.

**Comment by nlct** [comment]
The `openin_any` check was added because I asked if `texosquery` could be considered for TeX Live's restricted list as I thought it would be a useful tool. This meant that I had to tighten up the security settings, specifically for `texosquery-jre8.jar` (which is the only `texosquery` variant being considered for the restricted list). The main concern for the TL security team is that `texosquery-jre8` should honour TL's `p` or `r` values of `openin_any`, so I think I'll also allow `texosquery-jre8` to assume `a` if `openin_any` hasn't been set. 

There's no check for `openout_any` as `texosquery` doesn't create, edit or delete any files. On reflection, I don't think MiKTeX's `EnableWrite18` setting is relevant here. I haven't had a chance to look at it yet, but the name suggests that it's related to the shell escape which is independent of `openin_any`. The TeX code in `texosquery.tex` checks for either `\pdfshellescape` (pdfTeX) or `\shellescape` (XeTeX) to determine whether or not the shell escape is available. If `texosquery` is executed, then the shell escape was available. If the shell escape isn't available, then `texosquery` can't be executed, so there's no point in `texosquery` investigating the shell escape setting. (It would be useful if the TeX code could also check if piped shell escape is available, since `\TeXOSQuery` relies on it, but I don't know anyway of doing that. Again, that's something that can't be deferred to `texosquery` because if it's executed then the piped shell escape was successful.)

The `openin_any` setting determines whether or not TeX is allowed read-access to particular files (in addition to the operating system's read permissions). Commands such as `\openin` and `\input` and (for LaTeX) `\usepackage`, `\documentclass` and `\InputIfFileExists` should all obey `openin_any` (for TeX Live).

For example (assuming all the files exist), `openin_any=a` allows all the files in the following to be input:
```tex
\input foo
\input ../foo
\input subdir/foo
\input .subdir/foo
```
This ability to read any file that belongs to the user could potentially be exploited by malicious code. For example, a package or document class downloaded from an unreliable source could include code to read the user's private files and include information in PDF metadata that could then be harvested if the PDF was put online. (I've never encountered this kind of thing, but it is a concern.) This is why `texosquery-jre8.jar` and `texosquery.jar` don't allow file listings outside the current working directory, regardless of `openin_any`, to prevent malicious code from using `texosquery` to probe the filing system.

The `openin_any=r` restricted setting is unrelated to the restricted shell escape. This setting forbids hidden files, so in the above example, the last file `.subdir/foo.tex` can't be read since the initial dot denotes a hidden directory (on Unix-like systems). This results in the error message:
```
tex: Not reading from .subdir/foo (openin_any = r).
! I can't find file `.subdir/foo'.
```

The `openin_any=p` paranoid setting forbids all files forbidden by `openin_any=r` and additionally forbids any files outside the current working directory. So this setting not only forbids the hidden file `.subdir/foo.tex` but also the file `../foo.tex`:
```
tex: Not reading from ../foo (openin_any = p).
! I can't find file `../foo'.
```

This is what triggered the error for your example. Since `texosquery` couldn't determine a value for `openin_any`, it assumed `p`. The `--cwd` switch tries to return the full path for the current working directory. This function is an awkward border case as from `texosquery`'s point of view this file name isn't inside the current working directory (it actually is the cwd), so the `openin_any=p` setting forbids access.

If MikTeX has an equivalent setting to `openin_any` then the long run solution would be for `texosquery` to check for it if `kpsewhich` returns nothing for `openin_any`. If MikTeX doesn't have an equivalent, then it seems reasonable for `texosquery` to assume that read-access is permitted for any file (as long as the operating system and Java's security manager permit it).

Thank you for highlighting the problem.

**Comment by cweedall** [comment]
Thank you for the explanation.  I basically had two thought from what you said.

First, it seems to me that read-access will effectively always be allowed for MiKTeX users, even where it would be restricted (partially or completely outside the cwd) by users of most or all other TeX installations.  Possibly, this is ok as a short term thing, but I am a bit concerned that despite the unlikelihood, this could create security issues for these users alone.

Second, as was mentioned by Ulrike, a new feature could be requested so that `kpsewhich` does broadcast either `openin_any` or `EnableWrite18`.  Regardless, this approach would be a two-part process.  Implementing it on `texosquery` side and also on MiKTeX's side.

I guess I am a bit concerned about opening security up too much.  I just opened a prompt, when to my System32 folder in Windows, `set openin_any=a`, and ran `texosquery --cwd`.  This was not an elevated root/Admin) prompt.  It output the results correctly.  This seems to mean that if set up `texosquery` to assume a value of `a` if `openin_any` is not found by `kpsewhich`, then it would automatically open the entire system up for read access to `texosquery` on MiKTeX users' systems.  (I haven't looked into Java's security settings nor do I remember changing them, so I believe this applies for the default settings).

**Comment by nlct** [comment]
Even with `openin_any=a`, `texosquery-jre8.jar` has an additional security feature that prohibits file listings outside of the current working directory, so arbitrary files can't be found. (The same is true for `texosquery.jar`, but only `texosquery-jre8` is on the restricted list.)

The only information that can be obtained for files outside of the current working directory is the date/time stamp, the file size, the canonical path and the URI. The file contents can't be access with `texosquery-jre8`. If it's used within TeX's shell escape in order to obtain the full pathname of a file, it would require TeX's I/O commands to actually read the file (through `\openin` or `\input`).

So if `texosquery-jre8` has to fallback on `openin_any=a` because it can't determine the setting, the file I/O access is governed by the TeX distribution's actual security settings.

For example, `texosquery-jre8 -e ../foo.txt` will given the full pathname of `../foo.txt` but you can just as easily read the file contents with `\input ../foo.txt` (or with `\openin` or `\verbatiminput` etc). If the MiKTeX security setting prohibits I/O access outside of the current working directory then `\input` will fail. You can obtain the home path with `texosquery-jre8 -m` but you can just as easily obtain it with `kpsewhich --var-value=HOME` (or `kpsewhich --var-value=USERPROFILE` etc). In either case, you can't find the contents of the home directory (unless that happens to be the current working directory, but it's bad security to run TeX in the home directory instead of restricting it to a sub-directory).

Note that you shouldn't be able to use `set openin_any=a` in TeX's restricted mode. (That would be a serious security flaw if it was possible!) The aim of the `texosquery-jre8` security features is to protect the user in the event that it's run within TeX's shell escape in restricted mode. If you have access to the command prompt, then you also have access to `dir`, `del` etc. If the OS doesn't permit read access of a file then `texosquery-jre8` can't read it regardless of `openin_any`.

I'm going to close this issue now that `texosquery` will provide a fallback value in the event that `openin_any` is unavailable.
