### ISSUE TITLE
Enable usage in restricted shell escape

### ISSUE THREAD

**Issue by eg9** [nlct/texosquery#4]
The distributed `texosquery.cfg` (TeX Live 2017 pretest) file has

     % If the invoker name given above is on the restricted list,
     % allow it to be run in restricted mode:
     %\TeXOSQueryAllowRestricted

The last line should not be commented.

**Comment by nlct** [comment]
It's commented because the default is to use `texosquery.jar` (the Java 7 version) which isn't being considered for the restricted list. It should only be uncommented if both `texosquery-jre8` is added to the restricted list and the line defining `\TeXOSInvokerName` is changed to:
```tex
\def\TeXOSInvokerName{texosquery-jre8}
```
That's why the first line of the comment you included starts with "If", but I will edit it to clarify.

**Comment by eg9** [comment]
As far as I can see, `texosquery-jre8` has been added as good for the restricted shell in `texmf.cnf` for TeX Live 2017

**Comment by nlct** [comment]
As from v1.7, the default setting in the `texosquery.cfg` file is to use `texosquery-jre8.jar` and enable in restricted mode.
